import type { Metadata } from "next";
import { SITE_NAME, SITE_DESCRIPTION, getSiteUrl } from "@/lib/site";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(getSiteUrl()),
  title: {
    default: SITE_NAME,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  openGraph: {
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    type: "website",
    url: getSiteUrl(),
    siteName: SITE_NAME,
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="border-b border-slate-200 bg-white">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4">
            <a href="/" className="flex items-center gap-2">
              <span
                className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-500 text-sm font-bold text-white"
                aria-hidden
              >
                SC
              </span>
              <span className="text-lg font-semibold tracking-tight">{SITE_NAME}</span>
            </a>
            <nav aria-label="Primary">
              <a
                href="https://github.com"
                className="text-sm font-medium text-slate-500 hover:text-slate-900"
              >
                Source
              </a>
            </nav>
          </div>
        </header>
        <main>{children}</main>
        <footer className="mt-16 border-t border-slate-200 py-8 text-center text-sm text-slate-400">
          Built as a full-stack technical assessment · summaries and tags generated by AI
        </footer>
      </body>
    </html>
  );
}
