import type { Metadata, Viewport } from "next";
import Link from "next/link";
import { Inter, Fraunces } from "next/font/google";
import { SITE_NAME, SITE_DESCRIPTION, SITE_TAGLINE, getSiteUrl } from "@/lib/site";
import { ThemeToggle } from "@/components/ThemeToggle";
import { ToastProvider } from "@/components/Toaster";
import { LogoMark } from "@/components/LogoMark";
import "./globals.css";

const sans = Inter({ subsets: ["latin"], variable: "--font-sans", display: "swap" });
const display = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  axes: ["opsz"],
});

export const metadata: Metadata = {
  metadataBase: new URL(getSiteUrl()),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: ["reading list", "bookmarks", "AI summaries", "link saver", "content curation", "tags"],
  alternates: { canonical: "/" },
  openGraph: {
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    type: "website",
    url: "/",
    siteName: SITE_NAME,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafaf9" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0a09" },
  ],
  width: "device-width",
  initialScale: 1,
};

// Runs before first paint so the stored/system theme applies without a flash.
const themeScript = `(function(){try{var t=localStorage.getItem("theme");var d=t==="dark"||(t!=="light"&&window.matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",d);}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${display.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="flex flex-col">
        <a
          href="#main"
          className="sr-only z-50 rounded-md bg-accent px-3 py-2 text-accent-fg focus:not-sr-only focus:fixed focus:left-4 focus:top-4"
        >
          Skip to content
        </a>
        <ToastProvider>
          <header className="sticky top-0 z-30 border-b border-line/80 bg-canvas/80 backdrop-blur-md supports-[backdrop-filter]:bg-canvas/70">
            <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
              <Link href="/" className="group flex items-center gap-2.5 rounded-lg" aria-label={`${SITE_NAME} home`}>
                <LogoMark className="h-8 w-8" />
                <span className="font-display text-lg font-semibold tracking-tight">
                  Smart<span className="text-accent">Curator</span>
                </span>
              </Link>
              <nav aria-label="Primary" className="flex items-center gap-1">
                <Link href="/" className="btn-ghost hidden sm:inline-flex">
                  Library
                </Link>
                <ThemeToggle />
              </nav>
            </div>
          </header>
          <main id="main" className="flex-1">
            {children}
          </main>
          <footer className="border-t border-line">
            <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-2 px-4 py-6 text-sm text-fg-subtle sm:flex-row sm:px-6">
              <p>© {new Date().getFullYear()} {SITE_NAME}</p>
              <p>Summaries and tags are generated by Google Gemini and may contain mistakes.</p>
            </div>
          </footer>
        </ToastProvider>
      </body>
    </html>
  );
}
